# Generated by Django 3.0.5 on 2020-05-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200516_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theming',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика'},
        ),
    ]
