# Generated by Django 3.0.5 on 2020-05-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theming',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='theming',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Theme', verbose_name='Тема'),
        ),
    ]
