# Generated by Django 3.0.5 on 2020-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200516_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ManyToManyField(through='articles.Theming', to='articles.Theme'),
        ),
    ]
